### ISSUE TITLE
Dimensional error while running ``example_gymnast.py`` 

### ISSUE THREAD

**Issue by pulak-gautam** [BolunDai0216/PyMuJoCoBase#2]
While attempting to run ``example_gymnast.py``. I encounter this error:
```
PyMuJoCoBase/PyMuJoCoBase/examples/example_gymnast.py", line 42, in controller
    J = data.efc_J[:3, :3]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

```
I attempted to debug, it seems data.efc_J is actually a 1D array - ``[ 1.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]``, aligning with the API reference [here](https://mujoco.readthedocs.io/en/3.0.1/APIreference/APItypes.html#mjdata).

**Comment by BolunDai0216** [comment]
@pulak-gautam  In this case, probably the API was updated too. Feel free to do a PR!

**Comment by pulak-gautam** [comment]
@BolunDai0216 made a PR (#3)
